name: transactions_dbt
version: "1.0.0"
config-version: 2

profile: clickhouse

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
seed-paths: ["seeds"]

models:
  transactions_dbt:
    staging:
      materialized: view
    marts:
      materialized: table
